### ISSUE TITLE
The game doesn't work without Discord

### ISSUE THREAD

**Issue by WheatleyHDD** [LennyPhoenix/GodotDiscordSDK#13]
## Describe the bug
The game just doesn't start when Discord is closed

## To Reproduce
1. Close Discord
2. Run the game

## Additional context
I just used yours demo. I checked that CreateFlags has the value NoRequireDiscord. Debugger doesn't throw any errors. The game opens, the splash screen hangs, and after a small amount of time (5-10 seconds) the game window closes

**Comment by JezSonic** [comment]
Could you send there output logs?

**Comment by WheatleyHDD** [comment]
It's empty
![image](https://user-images.githubusercontent.com/37198050/114140325-73db0180-9953-11eb-932e-eaf8658623d9.png)

**Comment by JezSonic** [comment]
Are you on windows? If so, please send logs from system console that apperars with Godot

**Comment by JezSonic** [comment]
Also. Could you run Godot with --verbose argument for more logs?
I can't open that project right now and you know... Logs would be very helpful.
And what types of libraries do you use? Debug or Release?
What version of Godot do you use?

**Comment by WheatleyHDD** [comment]
I'm use release libraries and latest stable Godot Engine version 3.2.3

That's log from console with --verbose 
`Running: C:\Users\wheat\Desktop\Godot_v3.2.3-stable_win64.exe --path C:/Users/wheat/Documents/GodotDiscordSDK/demo --remote-debug 127.0.0.1:6007 --allow_focus_steal_pid 5164 --position 448,240 res://scenes/main.tscn
Godot Engine v3.2.3.stable.official - https://godotengine.org
Using GLES3 video driver
OpenGL ES 3.0 Renderer: GeForce GTX 1650 Ti/PCIe/SSE2
WASAPI: wFormatTag = 65534
WASAPI: nChannels = 2
WASAPI: nSamplesPerSec = 48000
WASAPI: nAvgBytesPerSec = 384000
WASAPI: nBlockAlign = 8
WASAPI: wBitsPerSample = 32
WASAPI: cbSize = 22
WASAPI: detected 2 channels
WASAPI: audio buffer frames: 1962 calculated latency: 44ms

CORE API HASH: 17947557007960061372
EDITOR API HASH: 513236543915789544
Loading resource: res://scripts/autoload/discord_manager.gd
Loading resource: res://discord_sdk/discord.gd
Loading resource: res://discord_sdk/core.gdns
Loading resource: res://discord_sdk/discord_game_sdk.gdnlib
Loading resource: res://discord_sdk/user.gdns
Loading resource: res://discord_sdk/user_manager.gdns
Loading resource: res://discord_sdk/image_dimensions.gdns
Loading resource: res://discord_sdk/image_handle.gdns
Loading resource: res://discord_sdk/image_manager.gdns
Loading resource: res://discord_sdk/activity_timestamps.gdns
Loading resource: res://discord_sdk/activity_assets.gdns
Loading resource: res://discord_sdk/party_size.gdns
Loading resource: res://discord_sdk/activity_party.gdns
Loading resource: res://discord_sdk/activity_secrets.gdns
Loading resource: res://discord_sdk/activity.gdns
Loading resource: res://discord_sdk/activity_manager.gdns
Loading resource: res://discord_sdk/presence.gdns
Loading resource: res://discord_sdk/relationship.gdns
Loading resource: res://discord_sdk/relationship_manager.gdns
Loading resource: res://discord_sdk/discord.gd
Loading resource: res://discord_sdk/user.gdns
Loading resource: res://discord_sdk/user_manager.gdns
Loading resource: res://discord_sdk/image_dimensions.gdns
Loading resource: res://discord_sdk/image_handle.gdns
Loading resource: res://discord_sdk/image_manager.gdns
Loading resource: res://discord_sdk/activity_timestamps.gdns
Loading resource: res://discord_sdk/activity_assets.gdns
Loading resource: res://discord_sdk/party_size.gdns
Loading resource: res://discord_sdk/activity_party.gdns
Loading resource: res://discord_sdk/activity_secrets.gdns
Loading resource: res://discord_sdk/activity.gdns
Loading resource: res://discord_sdk/activity_manager.gdns
Loading resource: res://discord_sdk/presence.gdns
Loading resource: res://discord_sdk/relationship.gdns
Loading resource: res://discord_sdk/relationship_manager.gdns
Loading resource: res://discord_sdk/discord.gd
Loading resource: res://discord_sdk/user.gdns
Loading resource: res://discord_sdk/image_dimensions.gdns
Loading resource: res://discord_sdk/image_handle.gdns
Loading resource: res://discord_sdk/image_manager.gdns
Loading resource: res://discord_sdk/activity_timestamps.gdns
Loading resource: res://discord_sdk/activity_assets.gdns
Loading resource: res://discord_sdk/party_size.gdns
Loading resource: res://discord_sdk/activity_party.gdns
Loading resource: res://discord_sdk/activity_secrets.gdns
Loading resource: res://discord_sdk/activity.gdns
Loading resource: res://discord_sdk/activity_manager.gdns
Loading resource: res://discord_sdk/presence.gdns
Loading resource: res://discord_sdk/relationship.gdns
Loading resource: res://discord_sdk/relationship_manager.gdns
Loading resource: res://discord_sdk/discord.gd
Loading resource: res://discord_sdk/user.gdns
Loading resource: res://discord_sdk/image_dimensions.gdns
Loading resource: res://discord_sdk/image_handle.gdns
Loading resource: res://discord_sdk/activity_timestamps.gdns
Loading resource: res://discord_sdk/activity_assets.gdns
Loading resource: res://discord_sdk/party_size.gdns
Loading resource: res://discord_sdk/activity_party.gdns
Loading resource: res://discord_sdk/activity_secrets.gdns
Loading resource: res://discord_sdk/activity.gdns
Loading resource: res://discord_sdk/activity_manager.gdns
Loading resource: res://discord_sdk/presence.gdns
Loading resource: res://discord_sdk/relationship.gdns
Loading resource: res://discord_sdk/relationship_manager.gdns
Loading resource: res://discord_sdk/discord.gd
Loading resource: res://discord_sdk/user.gdns
Loading resource: res://discord_sdk/image_dimensions.gdns
Loading resource: res://discord_sdk/image_handle.gdns
Loading resource: res://discord_sdk/activity_timestamps.gdns
Loading resource: res://discord_sdk/activity_assets.gdns
Loading resource: res://discord_sdk/party_size.gdns
Loading resource: res://discord_sdk/activity_party.gdns
Loading resource: res://discord_sdk/activity_secrets.gdns
Loading resource: res://discord_sdk/activity.gdns
Loading resource: res://discord_sdk/presence.gdns
Loading resource: res://discord_sdk/relationship.gdns
Loading resource: res://discord_sdk/relationship_manager.gdns
Loading resource: res://discord_sdk/discord.gd
Loading resource: res://discord_sdk/user.gdns
Loading resource: res://discord_sdk/image_dimensions.gdns
Loading resource: res://discord_sdk/image_handle.gdns
Loading resource: res://discord_sdk/activity_timestamps.gdns
Loading resource: res://discord_sdk/activity_assets.gdns
Loading resource: res://discord_sdk/party_size.gdns
Loading resource: res://discord_sdk/activity_party.gdns
Loading resource: res://discord_sdk/activity_secrets.gdns
Loading resource: res://discord_sdk/activity.gdns
Loading resource: res://discord_sdk/presence.gdns
Loading resource: res://discord_sdk/relationship.gdns
Loaded builtin certs
Loading resource: res://scenes/main.tscn
Loading resource: res://assets/theme.tres
Loading resource: res://assets/fonts/notosans_ui_regular.ttf
Loading resource: res://scripts/main.gd
Loading resource: res://icon.png
Loading resource: res://assets/fonts/notosans_ui_bold.ttf
Loading resource: res://scenes/menus/main.tscn
Loading resource: res://scripts/menus/main.gd
Loading resource: res://scenes/menus/users.tscn
Loading resource: res://scenes/menus/users/get_user.tscn
Loading resource: res://assets/fonts/header.tres
Loading resource: res://scripts/menus/users/get_user.gd
Loading resource: res://scenes/resource_displays/user.tscn
Loading resource: res://scripts/resource_displays/user.gd
Loading resource: res://scenes/menus/users/current_user.tscn
Loading resource: res://scripts/menus/users/current_user.gd
Loading resource: res://scenes/menus/images.tscn
Loading resource: res://scenes/menus/images/fetch.tscn
Loading resource: res://scripts/menus/images/fetch.gd
Loading resource: res://scenes/menus/activities.tscn
Loading resource: res://scenes/menus/activities/register_command.tscn
Loading resource: res://scripts/menus/activities/register_command.gd
Loading resource: res://scenes/menus/activities/register_steam.tscn
Loading resource: res://scripts/menus/activities/register_steam.gd
Loading resource: res://scenes/menus/activities/update_activity.tscn
Loading resource: res://scripts/menus/activities/update_activity.gd
Loading resource: res://scenes/resource_inputs/activity.tscn
Loading resource: res://scenes/resource_inputs/activity_timestamps.tscn
Loading resource: res://scripts/resource_inputs/activity_timestamps.gd
Loading resource: res://scenes/resource_inputs/activity_assets.tscn
Loading resource: res://scripts/resource_inputs/activity_assets.gd
Loading resource: res://scenes/resource_inputs/activity_party.tscn
Loading resource: res://scenes/resource_inputs/party_size.tscn
Loading resource: res://scripts/resource_inputs/party_size.gd
Loading resource: res://scripts/resource_inputs/activity_party.gd
Loading resource: res://scenes/resource_inputs/activity_secrets.tscn
Loading resource: res://scripts/resource_inputs/activity_secrets.gd
Loading resource: res://scripts/resource_inputs/activity.gd
Loading resource: res://scenes/menus/activities/clear_activity.tscn
Loading resource: res://scripts/menus/activities/clear_activity.gd
Loading resource: res://scenes/menus/activities/send_request_reply.tscn
Loading resource: res://scripts/menus/activities/send_request_reply.gd
Loading resource: res://scenes/menus/activities/send_invite.tscn
Loading resource: res://scripts/menus/activities/send_invite.gd
Loading resource: res://scenes/menus/activities/accept_invite.tscn
Loading resource: res://scripts/menus/activities/accept_invite.gd
Loading resource: res://scenes/menus/activities/activity_joined.tscn
Loading resource: res://scripts/menus/activities/activity_joined.gd
Loading resource: res://scenes/menus/activities/activity_spectated.tscn
Loading resource: res://scripts/menus/activities/activity_spectated.gd
Loading resource: res://scenes/menus/activities/activity_join_requested.tscn
Loading resource: res://scripts/menus/activities/activity_join_requested.gd
Loading resource: res://scenes/menus/activities/activity_invite.tscn
Loading resource: res://scripts/menus/activities/activity_invite.gd
Loading resource: res://scenes/resource_displays/activity.tscn
Loading resource: res://scenes/resource_displays/activity_timestamps.tscn
Loading resource: res://scripts/resource_displays/activity_timestamps.gd
Loading resource: res://scenes/resource_displays/activity_secrets.tscn
Loading resource: res://scripts/resource_displays/activity_secrets.gd
Loading resource: res://scenes/resource_displays/activity_party.tscn
Loading resource: res://scenes/resource_displays/party_size.tscn
Loading resource: res://scripts/resource_displays/party_size.gd
Loading resource: res://scripts/resource_displays/activity_party.gd
Loading resource: res://scenes/resource_displays/activity_assets.tscn
Loading resource: res://scripts/resource_displays/activity_assets.gd
Loading resource: res://scripts/resource_displays/activity.gd
Loading resource: res://scenes/menus/relationships.tscn
Loading resource: res://scenes/menus/relationships/filter.tscn
Loading resource: res://scripts/menus/relationships/filter.gd
Loading resource: res://scenes/code_editor.tscn
Loading resource: res://assets/fonts/sourcecodepro_regular.otf
Loading resource: res://scripts/code_editor.gd
Loading resource: res://scenes/menus/relationships/get.tscn
Loading resource: res://scripts/menus/relationships/get.gd
Loading resource: res://scenes/resource_displays/relationship.tscn
Loading resource: res://scripts/resource_displays/relationship.gd
Loading resource: res://scenes/resource_displays/presence.tscn
Loading resource: res://scripts/resource_displays/presence.gd
Loading resource: res://scenes/menus/relationships/get_at.tscn
Loading resource: res://scripts/menus/relationships/get_at.gd
Loading resource: res://scenes/menus/relationships/count.tscn
Loading resource: res://scripts/menus/relationships/count.gd
Loading resource: res://scenes/menus/relationships/relationship_update.tscn
Loading resource: res://scripts/menus/relationships/relationship_update.gd
Socket error: 10054`

**Comment by JezSonic** [comment]
`Socket error: 10054`  is usually caused accidentally when the user shuts down the software or closes the connection while the computer is attempting to connect with a server. More serious causes of this error are the Internet connection suddenly dropping or a proxy server disabling server connections. As with all errors, the firewall also could be acting up and causing the connection to break.

The overall reason why this socket error occurs is because the server connection has been broken by something outside the server. Most of the time, this is an action caused, either purposefully or accidentally, by the user. When 10054 manifests, as with other errors, the first thing that the user should do is to temporarily disable the firewall, because firewalls sometimes break good connections, thinking they are bad.

If the problem occurred because of an accidental or manual shutdown of the program, then this will be even easier to fix than the firewall method. Sometimes, when a user is attempting to connect to a server, he or she will close the program. This may be because he no longer needs to connect to the server or because the program was closed mistakenly. In this instance, he can just start the program again and the connection should work.

A break in the Internet connection also can cause a socket error 10054. As with the program, this can occur manually. If the user is not at fault for breaking the Internet connection, he should check the modem, router, and any internal device connecting to the Internet to ensure they are working. Manually resetting the device and calling the Internet service provider (ISP) can help get the Internet back online. In more serious cases, the device may have to be repaired or replaced.

Another reason for this error is that the user is using a proxy server to mask his computer address. This happens if the server is attempting to connect to the computer’s inherent address, and not the proxy server. If this occurs, the user can manually tell the server to connect to the proxy and not directly to the computer. Otherwise, the connection will keep breaking.

**Comment by JezSonic** [comment]
https://www.easytechjunkie.com/what-are-the-common-causes-of-socket-error-10054.htm

**Comment by LennyPhoenix** [comment]
Hey, what OS are you currently using? I was getting an issue like this while testing on Linux.

**Comment by LennyPhoenix** [comment]
Can you also verify that this issue doesn't occur when you don't call `discord.create`?

**Comment by WheatleyHDD** [comment]
I checked on Windows 10. Yes, when commenting on a line with `call_deferred("create_core")` in file `res://scripts/autoload/discord_manager.gd` the application starts without problems.
![image](https://user-images.githubusercontent.com/37198050/114168369-86653300-9973-11eb-8ff0-bad5cac30419.png)

**Comment by LennyPhoenix** [comment]
How did you compile the library?
Also check a couple things quickly:
- Check you are using the latest version of the library.
- Check you are using v2.5.6 of the Discord Game SDK.

**Comment by WheatleyHDD** [comment]
I downloaded the latest library from the Github Actions page. Discord GameSDK I checked, version 2.5.6

**Comment by LennyPhoenix** [comment]
Did you download the Debug or Release build?

**Comment by WheatleyHDD** [comment]
I download release build

**Comment by LennyPhoenix** [comment]
Ok, ill see if I can replicate the issue and solve it

**Comment by LennyPhoenix** [comment]
Good news! I identified the issue, looks like I was running core->destroy when I didn't need to: [`d40f0a8`](https://github.com/LennyPhoenix/GodotDiscordSDK/commit/d40f0a80f6099a7ee028f5e6e558382981fcbb55)
