### ISSUE TITLE
Image Fetch Fails

### ISSUE THREAD

**Issue by JezSonic** [LennyPhoenix/GodotDiscordSDK#20]
## System Info

- Godot Version: 3.3.0
- Operating System: Windows 10 Pro
- Compilation Method: release, from github actions artifacts

**Describe the bug**
After enabling discord integration the saving data icon should be an currently logged in discord user's profile picture

**To Reproduce**
1. Run the game
2. Enable discord integration if needed
3. See error

**Expected behavior**
If integration was enabled, image should be displayed properly

**Additional context**
Discord is getting user info properly, but while creating image, debugger prints `ITERNAL_ERROR`

## Checklist

- [x] I have checked for duplicate issues.
- [x] I have provided a detailed description of the issue.
- [x] I have provided reproduction steps (if applicable).

**Comment by LennyPhoenix** [comment]
This is a known issue with the game SDK, waiting for an upstream fix.

https://github.com/discord/gamesdk-and-dispatch/issues/122

**Comment by LennyPhoenix** [comment]
Fixed upstream.
