### ISSUE TITLE
Error while trying to display User Profile Picture

### ISSUE THREAD

**Issue by JezSonic** [LennyPhoenix/GodotDiscordSDK#4]
**Describe the bug**
> When running test project, Godot can't load my profile picture, cause user image given by SDK have different size than Godot needs and it threws error "got x bytes of data instead of excepted y"

**To Reproduce**
> Just run test project

**Expected behaviour**
> TextureRect displays User Image properly

**Screenshots**
> ![image](https://user-images.githubusercontent.com/45912895/107035963-30301400-67b9-11eb-8abe-e720f846877f.png)

**Additional context**
> Changing image format and multipling dimensions to make image bytes match number of bytes that Godot is waiting for doesn't fix this. There's no error, byt image is not displayed

**Please confirm the following:** *(Place an `X` between the square brackets)*
- [x] I have checked for duplicate issues.
- [x] I have provided a detailed description of the issue.
- [x] I have provided reproduction steps (if applicable).

**Comment by LennyPhoenix** [comment]
Could you try adding these lines of code to the `fetch_callback`:
```gds
print(dimensions.height, ":", dimensions.width)
print(handle.size)
```

like so:
![image](https://user-images.githubusercontent.com/57148878/107031851-c446af00-67aa-11eb-9afb-42346188626e.png)

The likely issue is that the sdk is returning a square version of the image, but get_dimensions returns the original image dimensions.

**Comment by JezSonic** [comment]
> Could you try adding these lines of code to the `fetch_callback`:
> 
> ```
> print(dimensions.height, ":", dimensions.width)
> print(handle.size)
> ```
> 
> like so:
> ![image](https://user-images.githubusercontent.com/57148878/107031851-c446af00-67aa-11eb-9afb-42346188626e.png)
> 
> The likely issue is that the sdk is returning a square version of the image, but get_dimensions returns the original image dimensions.

sure, let me finish lessons and i'll do it

**Comment by JezSonic** [comment]
![image](https://user-images.githubusercontent.com/45912895/107035963-30301400-67b9-11eb-8abe-e720f846877f.png)

You have everything there, i also have updated issue

**Comment by LennyPhoenix** [comment]
Ok, so it looks like the issue is that `ImageDimensions` is the original image dimensions, but `get_data` will return the resized image bytes to fit the size we passed to the `ImageHandle`, so all we have to do is replace the fetch callback with this:
```gdscript
func fetch_callback(result: int, handle: Discord.ImageHandle) -> void:
	if result != Discord.Result.OK:
		print(
			"Failed to fetch image handle: ",
			enum_to_string(Discord.Result, result)
		)
	else:
		print("Fetched image handle, ", handle.id, ", ", handle.size)

		var data = images.get_data(handle)
		if data is int:
			print(
				"Failed to get image data: ",
				enum_to_string(Discord.Result, data)
			)
		else:
			var image: = Image.new()
			image.create_from_data(
				handle.size, handle.size,
				false,
				Image.FORMAT_RGBA8,
				data
			)
			image.unlock()
			var tex: = ImageTexture.new()
			tex.create_from_image(image)
			texture_rect.texture = tex
			OS.window_size = Vector2(handle.size, handle.size)
```

**Comment by LennyPhoenix** [comment]
Let me know if it still doesnt work after replacing this function ^

I'm going to add something to the docs about this to prevent issues in future.

**Comment by JezSonic** [comment]
:/
![image](https://user-images.githubusercontent.com/45912895/107038267-8c486780-67bc-11eb-960f-af82dc6244f1.png)

**Comment by LennyPhoenix** [comment]
Could you try saving the resulting image to a png?
```gdscript
image.save_png("res://avatar.png")
```
![image](https://user-images.githubusercontent.com/57148878/107038876-14c30a00-67b5-11eb-8f83-3f7a59f09117.png)

**Comment by JezSonic** [comment]
![avatar](https://user-images.githubusercontent.com/45912895/107044283-5dce8a80-67c4-11eb-9988-50c2a7d22c97.png)
there you have the result

**Comment by LennyPhoenix** [comment]
Could you please send you whole main.gd file? I can't seem to replicate this issue myself, but I'll try using an alt account with smaller pfp later.

**Comment by LennyPhoenix** [comment]
OK, I think I've figure out the issue, so I'm going to implement a fix now, let me know if it still doesn't work.

**Comment by JezSonic** [comment]
Ok, thanks

**Comment by JezSonic** [comment]
> Could you please send you whole main.gd file? I can't seem to replicate this issue myself, but I'll try using an alt account with smaller pfp later.

I can't do it now... I'll do it as fast as possible.

**Comment by JezSonic** [comment]
Btw. If you prefer we can talk on discord, you have my nick and tag on the screen (Futrzak#7813)
